on: workflow_dispatch

jobs:


  create_release_branch:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Create release branch
        run: git checkout -b release/${{ github.run_number }}
      - name: Push new branch
        run: git push origin release/${{ github.run_number }}

  create_release_docker:
    needs: [create_release_branch]
    runs-on: ubuntu-latest
    steps:
      - name: Docker Auth
        run: docker login --username oauth --password ${{ github.YANDEX_AUTH }} cr.yandex
      - name: Create Docker image
        run: docker image build -t cr.yandex/${{github.YC_REGISTRY_ID}}/app:${{ github.run_number }} .
      - name: Pull Docker image
        run: docker pull cr.yandex/${{github.YC_REGISTRY_ID}}/app:${{ github.run_number }}
      - name: Create Docker image current
        run: docker image build -t cr.yandex/${{github.YC_REGISTRY_ID}}/app:${{ github.run_number }}_latest .
      - name:  Pull Docker image current
        run: docker pull cr.yandex/${{github.YC_REGISTRY_ID}}/app:${{ github.run_number }}_latest
