name: Release Production
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "Version to release"

jobs:
  run_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Yandex Cloud CR "Login" Action for GitHub Actions
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Deploy COI VM
        id: deploy-coi
        uses: yc-actions/yc-coi-deploy@v2
        env:
          CR_REGISTRY: ${{secrets.YC_REGISTRY_ID}}
          CR_REPOSITORY: crp2i96436f2665d759c/app
          IMAGE_TAG: cr.yandex/${{secrets.YC_REGISTRY_ID}}/app:${{ inputs.version }}_latest
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: b1glfd63reoaohe1mnsd
          vm-name: irkatyman

  add_issue_comment:
    needs: [run_docker]
    runs-on: ubuntu-latest
    steps:
      - name: Put current date into a variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{inputs.issue-number}}
          body: |
            **Prod**:
            - Date: ${{env.NOW}}
            - Author: ${{ github.triggering_actor }}
