on: workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run test

  create_release_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Create release branch
        run: git checkout -b release/${{ github.run_number }}
      - name: Push new branch
        run: git push origin release/${{ github.run_number }}

  create_release_docker:
    needs: [create_release_branch]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Yandex Cloud CR "Login" Action for GitHub Actions
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Create Docker image
        run: |
          docker build -t cr.yandex/${{secrets.YC_REGISTRY_ID}}/app:${{ github.run_number }} .
          docker push cr.yandex/${{secrets.YC_REGISTRY_ID}}/app:${{ github.run_number }}

      - name: Create Docker image current
        run: |
          docker image build -t cr.yandex/${{secrets.YC_REGISTRY_ID}}/app:${{ github.run_number }}_latest .
          docker push cr.yandex/${{secrets.YC_REGISTRY_ID}}/app:${{ github.run_number }}_latest

      - name: Push tag
        uses: EndBug/latest-tag@latest
        with:
          tag-name: ${{github.run_number}}

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Create an issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Release ${{github.run_number}}
          body: |
            ## Release ${{github.run_number}}: Issue:
            
            - Date: $NOW
            - Author: ${{ github.triggering_actor }}
            - Version: ${{ github.run_number }}
            - Commits:
            - YC Docker: cr.yandex/${{secrets.YC_REGISTRY_ID}}/app:${{ github.run_number }}
